// <auto-generated />
using Lol.Yovo4.DataStructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lol.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20230228114456_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Lol.Yovo4.DataStructures.DBYoloV4", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BBox0")
                        .HasColumnType("REAL");

                    b.Property<float>("BBox1")
                        .HasColumnType("REAL");

                    b.Property<float>("BBox2")
                        .HasColumnType("REAL");

                    b.Property<float>("BBox3")
                        .HasColumnType("REAL");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageID");

                    b.ToTable("DBYoloV4s");
                });
#pragma warning restore 612, 618
        }
    }
}
